gpus: '-1' #or -1 for cpu
exp_id: 'base_detect'


dataset:
  data_dir: '../data/plate'
  num_classes: &num_classes 1
  label_name: ['corner']
  mean: [0.408, 0.447, 0.470]
  std: [0.289, 0.274, 0.278]
  max_object: 100
  radius: 4                 # radius of keypoint on heatmap


model:
  arch: 'dla_34'
  head_conv: 256
  heads:
    hm: *num_classes
    reg: 2
  input_h: 512
  input_w: 512
  pad: 31
  down_ratio: 4

train:
  num_epochs: 140
  batch_size: 1
  lr: 1.25e-4
  lr_step: [90,120]
  num_workers: 4
  val_intervals: 5
  save_all: False         # save after each validation
  metric: 'loss'
  reg_loss: 'l1'      # or sl1
  num_stacks: 1
  hm_weight: 1
  off_weight: 1

  master_batch_size: -1
  resume_path: ''             # checkpoint path

  num_iters: -1
  debug: False
  seed: 317
  not_cuda_benchmark: True

  hide_data_time: False
  print_iter: True


predictor:
  weight: "../weights/model_last_210_v3.pth"
  scale: 1.0
  threshold: 0.25
  fix_res: True
